version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yrdsUTxubbCktFOBkGYPcyNvOsqbYofh
      MYSQL_DATABASE: epolldb
      MYSQL_USER: root
      MYSQL_PASSWORD: yrdsUTxubbCktFOBkGYPcyNvOsqbYofh
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_boot_app
    restart: always
    environment:
      DB_URL: jdbc:mysql://mysql:3306/mydb
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
